server:
    context-path: /manager

    
login:
    noLoginAccess: 
        - /index.html
        - /doLogin
        - /loginOut
        - /captcha-img
        - /noAccess
        - /noLogin
        - /error
    
    noAccess:
        - /homePage.html
        - /listMenu
        - /listSubDept
        - /listGrantUrls
        - /listResourceForRole
        - /listResourceForRole
        - /listResourceForAccount
        - /grantRoleForAccount
        - /grantResourceForRole
        - /grantResourceForAccount
        - /listAllResource
        - /system/account/accountMgt.html
        - /listRoleForAccount
        - /listAccountForRole
        - /grantAccountForRole
        
    isUseCaptcha: false
      
project:  
    code: manager
    name: 管理台系统
    defaultPassword: 123456
      
mybatis: 
    type-aliases-package: com.neo.entity
    config: classpath:/mybatis/mybatis_config.xml
    mapper-locations: classpath*:com/cxp/**/mapper/*.xml

spring:
    datasource: 
        name: login
        url: jdbc:mysql://localhost:3306/cxpCode?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 111111
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
       
    
    resources:
        static-locations: classpath:/resources/,classpath:/html/
    mvc:
        view:
            prefix: classpath:/view/
            suffix: .jsp
        static-path-pattern: /**
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss